homeassistant:
    name: Home
    latitude: 52.08151370769672
    longitude: 5.118844863027334
    elevation: 7
    temperature_unit: C
    time_zone: Europe/Amsterdam
    customize: !include_dir_merge_named customize

history:

logbook:

frontend:

sun:

discovery:

updater:

api:

mqtt:

recorder:
    purge_days: 7

nest:
    username: !secret nest_usr
    password: !secret nest_pass

thermostat:
    platform: nest

#router
device_tracker:
-   platform: asuswrt
    protocol: telnet
    host: 192.0.0.1
    username: !secret asus_usr
    password: !secret asus_pass
    scan_interval: 60
    interval_seconds: 30
    consider_home: 180

# keyboard cmds - not working on macOS for now
# keyboard:

media_player:
    platform: plex

notify:
    platform: pushbullet
    api_key: !secret push_api
    name: jonni

camera:
    platform: generic
    still_image_url: http://cdn.knmi.nl/knmi/map/page/weer/actueel-weer/neerslagradar/WWWRADARLGT_loop.gif
    name: Weather Map

weblink:
    entities:
      - name: Router
        url: !secret router_url
        icon: mdi:router-wireless
      - name: Plex
        url: !secret plex_url
        icon: mdi:chevron-right
      - name: Transmission
        url: !secret trans_url
        icon: mdi:cloud-download
      - name: Sonarr
        url: !secret sonarr_url
        icon: mdi:calendar
      - name: Couchpotato
        url: !secret couch_url
        icon: mdi:movie
      - name: Plex Requests
        url: !secret requests_url
        icon: mdi:comment-question-outline
      - name: PlexPy
        url: !secret plexpy_url
        icon: mdi:chart-bar
      - name: Glances
        url: !secret glances_url
        icon: mdi:server

http:
    api_password: !secret http_pass

sensor: !include_dir_merge_list sensors

switch: !include switches.yaml

group: !include_dir_merge_named groups

scene: !include_dir_merge_list scenes

script: !include scripts.yaml

automation: !include_dir_merge_list automations

alexa: !include alexa.yaml